name: trip_budgeter_2410
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  firebase_core: ^3.6.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  bcrypt: ^1.1.3
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/background_welcome.jpg
    - assets/background_sign_in.jpg
    - assets/background_register.jpg
    - assets/background_home.png
    - assets/background_home2.png


  uses-material-design: true